### PR TITLE
Prototype for infrared face recognition. #4

### PR DESCRIPTION
**Pull request by vandit98**
hi 
I have added a sample code for detecting  person using infrared camera. I hope i am going in the right direction. Let me know how to extend it or what more features should i add to code.

### CODE REVIEW

**Review by Deep-ghosty — CHANGES_REQUESTED** [review]
Just mail a demo video to me andpull the dataset too or its link to download it .

**Comment by vandit98** [comment]
hi
Below i have attached a sample video.
Also added the link to download the pretrained model file.

**Comment by Deep-ghosty** [comment]
i can see any video link

**Comment by Deep-ghosty** [comment]
where is the video

**Comment by vandit98** [comment]
Here is the link.
https://drive.google.com/file/d/1udQqmp8f3kXZ8qEcktszMGFqXjPrcYL4/view?usp=sharing

**Comment by Deep-ghosty** [comment]
is it work when lights r off because the infrared is for the time when driver drives in night time

**Comment by vandit98** [comment]
yes it does.
here is the video link for the case when lights are off.
https://drive.google.com/file/d/1u8XaX-FObQKfc3ZQh4wBqjSkeAeEjVwN/view?usp=sharing

**Comment by Deep-ghosty** [comment]
what u have done in mobile that providing u the output
i

**Comment by Deep-ghosty** [comment]
to see the parameter user have to use phone or on desktop it will show same

**Comment by vandit98** [comment]
i am using phone just to produce the infrared image since i dont have any infrared camera.
If the live video capturing camera (desktop ) can capture the infrared image then we are good to go.

**Comment by Deep-ghosty** [comment]
Ok u r using any application for it how u r doing this in phone . please
eloborate

**Comment by vandit98** [comment]
I am just using my code for detecting a human face.
Now in order to produce a infrared image, i am  using any random image(in my phone ) from the internet and show it in front of my laptop(where code is running) camera.
The code is able to locate the human face from that.

**Comment by Deep-ghosty** [comment]
Is there any progress till above ?
@vandit98

**Comment by vandit98** [comment]
here is the sample video of how its working
https://drive.google.com/file/d/1uKbR9qtVJtSmbWM1DUEL2kj4f6-t10-b/view?usp=sharing

**Comment by vandit98** [comment]
Added the code as well for the same.

**Review by Deep-ghosty — COMMENTED** [review]
I have to see the optimisation of this but i really appreciate the work after that i will surely merge it.

**Comment by vandit98** [comment]
Sure

**Review by Deep-ghosty — APPROVED** [review]

**Pull request merged**
